[project]
name = "backend"
version = "0.1.0"
description = "Repository for Jannes' and Sarah's BA on proteoforms and graphs."
authors = [{ name = "sarah", email = "sarah.vogels@aol.de" }]
readme = "README.md"
requires-python = ">=3.10,<3.12"
dependencies = [
    "django>=5.2,<6",
    "djangorestframework>=3.16.0,<4",
    "django-cors-headers>=4.7.0,<5",
    "python-decouple>=3.8,<4",
    "networkx>=3.4.2,<4",
    "protgraph",
    "requests>=2.32.4,<3",
]

[dependency-groups]
dev = [
    "pytest>=8.3.5,<9",
    "pytest-django>=4.11.1,<5",
    "coverage>=7.8.0,<8",
]

[tool.uv.sources]
protgraph = { git = "https://github.com/Tisch-hinten-rechts/ProtGraph.git", branch = "dev" }

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
