// Disclaimer: This code was generated by an AI language model, though checked and adjusted by a human.

/**
 * DAG Search Service
 * Provides string search functionality over the DAG structure (nodes and edges)
 * Uses KMP algorithm for efficient pattern matching
 */

import type { Node, Edge } from "@xyflow/react";
import { kmpSearchWithContext } from "./kmp-algorithm";
import {
  type NodeMatch,
  NodeSearchField,
  type PathMatch,
  type SearchOptions,
  type SearchResults,
} from "./types.ts";

/**
 * Preprocessed search index for faster repeated searches
 */
export class DAGSearchIndex {
  private nodes: Node[];
  private edges: Edge[];
  private nodeTextCache: Map<string, Map<string, string>>;

  constructor(nodes: Node[], edges: Edge[]) {
    this.nodes = nodes;
    this.edges = edges;
    this.nodeTextCache = new Map();
    this.buildCache();
  }

  /**
   * Build cache of searchable text fields for all nodes and edges
   * This preprocessing step improves search performance for repeated queries
   */
  private buildCache(): void {
    // Build node cache
    for (const node of this.nodes) {
      const textFields = new Map<string, string>();

      if (node.data) {
        // Extract sequence
        if (node.data.sequence) {
          textFields.set(NodeSearchField.SEQUENCE, String(node.data.sequence));
        }

        // Extract intensities string
        if (node.data.intensitiesString) {
          textFields.set(
            NodeSearchField.INTENSITIES,
            String(node.data.intensitiesString),
          );
        }

        // Extract partial peptide string (only the part of the sequence that is covered by peptides)
        // This is redundant for the current splitting of nodes but allows flexibility if splitting changes in the future
        if (
          node.data.peptidesString &&
          node.data.peptidesString !== "None" &&
          node.data.sequence
        ) {
          const peptides = String(node.data.peptidesString)
            .split(",")
            .map((p) => p.trim());
          const sequence = String(node.data.sequence);
          let partialPeptideSeq = "";

          // create a valid subset of the sequence that is covered by peptides
          // for multiple peptides, overlap them
          const coverage: boolean[] = new Array(sequence.length).fill(false);

          for (const peptide of peptides) {
            const indexOfPeptideInSequence = sequence.indexOf(peptide);
            const indexOfSequenceInPeptide = peptide.indexOf(sequence);

            // Case 1: peptide is fully encapsulated substring of the node
            if (indexOfPeptideInSequence !== -1) {
              for (
                let i = indexOfPeptideInSequence;
                i < indexOfPeptideInSequence + peptide.length;
                i++
              ) {
                coverage[i] = true;
              }
              continue; // check next peptide
            }

            // Case 2: node is fully encapsulated substring of the peptide
            if (indexOfSequenceInPeptide !== -1) {
              for (let i = 0; i < sequence.length; i++) {
                coverage[i] = true;
              }
              break; // no need to check other peptides for this node
            }

            // Case 3: end of peptide overlaps with start of node
            if (
              peptide.endsWith(
                sequence.substring(
                  0,
                  Math.min(peptide.length, sequence.length),
                ),
              )
            ) {
              const overlapLength =
                peptide.length -
                sequence.indexOf(
                  sequence.substring(
                    0,
                    Math.min(peptide.length, sequence.length),
                  ),
                );
              for (let i = 0; i < overlapLength; i++) {
                coverage[i] = true;
              }
              continue;
            }

            // Case 4: start of peptide overlaps with end of node
            if (
              peptide.startsWith(
                sequence.substring(
                  Math.max(0, sequence.length - peptide.length),
                  sequence.length,
                ),
              )
            ) {
              const overlapStart = sequence.length - peptide.length;
              for (
                let i = Math.max(0, overlapStart);
                i < sequence.length;
                i++
              ) {
                coverage[i] = true;
              }
            }
          }

          for (let i = 0; i < sequence.length; i++) {
            if (coverage[i]) {
              // add tab separators for non-continous coverage
              if (partialPeptideSeq.length > 0 && !coverage[i - 1]) {
                partialPeptideSeq += "\t";
              }
              partialPeptideSeq += sequence[i];
            }
          }

          textFields.set(NodeSearchField.PEPTIDES, partialPeptideSeq || "None");
        }
      }

      this.nodeTextCache.set(node.id, textFields);
    }

    console.log("DAGSearchIndex: Cache built for nodes.");
  }

  /**
   * Search in nodes
   */
  searchNodes(
    pattern: string,
    fields: NodeSearchField[] = [NodeSearchField.SEQUENCE],
    options: SearchOptions = {},
  ): NodeMatch[] {
    const { contextLength = 10, maxResults } = options;

    const matches: NodeMatch[] = [];
    let resultCount = 0;

    for (const node of this.nodes) {
      if (maxResults && resultCount >= maxResults) {
        break;
      }

      const textFields = this.nodeTextCache.get(node.id);
      if (!textFields) continue;

      for (const field of fields) {
        const text = textFields.get(field);
        if (!text || text === "None" || text === "") continue;

        const fieldMatches = kmpSearchWithContext(text, pattern, contextLength);

        if (fieldMatches.length > 0) {
          matches.push({
            nodeId: node.id,
            node,
            field,
            matches: fieldMatches,
            totalMatches: fieldMatches.length,
          });
          resultCount++;

          if (maxResults && resultCount >= maxResults) {
            break;
          }
        }
      }
    }

    return matches;
  }

  /**
   * Search across paths (multiple connected nodes)
   * This enables finding patterns that span across node boundaries
   * Deduplicates matches so each unique occurrence (by node IDs and match positions) appears only once
   **/
  searchPaths(pattern: string, options: SearchOptions = {}): PathMatch[] {
    const { contextLength = 10, maxResults, maxPathLength = 5 } = options;
    const visitedPaths = new Set<string>();

    // Track unique matches by their node IDs and match positions
    // Key format: "nodeId1,nodeId2,...@index1,index2,..."
    const uniqueMatches = new Map<string, PathMatch>();

    // Build adjacency list from edges
    const adjacencyList = new Map<string, string[]>();
    for (const edge of this.edges) {
      if (!adjacencyList.has(edge.source)) {
        adjacencyList.set(edge.source, []);
      }
      adjacencyList.get(edge.source)!.push(edge.target);
    }

    // DFS to generate all paths up to maxPathLength
    const generatePaths = (
      currentNode: Node,
      currentPath: Node[],
      depth: number,
    ): void => {
      if (depth > maxPathLength) return;
      if (maxResults && uniqueMatches.size >= maxResults) return;

      currentPath.push(currentNode);

      if (currentPath.length >= 2) {
        const pathKey = currentPath.map((n) => n.id).join("->");

        // Skip if we've already searched this exact path
        if (!visitedPaths.has(pathKey)) {
          visitedPaths.add(pathKey);

          // Combine sequences from all nodes in the path
          const sequences = currentPath
            .map((node) => {
              const textFields = this.nodeTextCache.get(node.id);
              return textFields?.get(NodeSearchField.SEQUENCE) || "";
            })
            .filter((seq) => seq && seq !== "None" && seq !== "");

          if (sequences.length > 0) {
            const combinedSequence = sequences.join("");
            const pathMatches = kmpSearchWithContext(
              combinedSequence,
              pattern,
              contextLength,
            );

            if (pathMatches.length > 0) {
              // Calculate which nodes each match spans across
              const nodeLengths: number[] = [];
              let cumulativeLength = 0;

              for (const node of currentPath) {
                const textFields = this.nodeTextCache.get(node.id);
                const seq = textFields?.get(NodeSearchField.SEQUENCE) || "";
                if (seq && seq !== "None" && seq !== "") {
                  nodeLengths.push(cumulativeLength);
                  cumulativeLength += seq.length;
                }
              }

              // For each match, determine which nodes it spans and create a unique key
              for (const match of pathMatches) {
                const matchStart = match.startIndex;
                const matchEnd = match.endIndex;

                // Find which nodes this match touches
                const touchedNodeIds: string[] = [];

                for (let i = 0; i < nodeLengths.length; i++) {
                  const nodeStart = nodeLengths[i];
                  const nodeEnd =
                    i < nodeLengths.length - 1
                      ? nodeLengths[i + 1]
                      : cumulativeLength;

                  // Check if match overlaps with this node's sequence
                  if (matchStart < nodeEnd && matchEnd > nodeStart) {
                    touchedNodeIds.push(currentPath[i].id);
                  }
                }

                // Create unique key based on touched nodes
                const uniqueKey = `${touchedNodeIds.join(",")}`;

                // Check if this match should be registered
                // A match should NOT be registered if its touchedNodeIds are a subset
                // of any existing match's pathIds (meaning it's already been found in a longer path)
                let shouldRegister = true;

                for (const existingMatch of uniqueMatches.values()) {
                  const existingPathIds = existingMatch.pathIds;

                  // Check if all touchedNodeIds are in existingPathIds
                  const isSubset = touchedNodeIds.every((id) =>
                    existingPathIds.includes(id),
                  );

                  if (isSubset) {
                    // This match has already been registered in a longer path
                    // Skip registration regardless of position (position differs based on path start)
                    shouldRegister = false;
                    break;
                  }
                }

                // Only add if this match hasn't been found before
                if (shouldRegister && !uniqueMatches.has(uniqueKey)) {
                  // Store the path that contains this match
                  uniqueMatches.set(uniqueKey, {
                    path: [...currentPath],
                    pathIds: currentPath.map((n) => n.id),
                    combinedSequence,
                    matches: [match], // Store only this specific match for this path
                    totalMatches: 1,
                  });
                }
              }
            }
          }
        }
      }

      // Continue DFS to neighbors
      const neighbors = adjacencyList.get(currentNode.id) || [];
      for (const neighborId of neighbors) {
        const neighborNode = this.nodes.find((n) => n.id === neighborId);
        if (neighborNode && !currentPath.some((n) => n.id === neighborId)) {
          generatePaths(neighborNode, [...currentPath], depth + 1);
        }
      }
    };

    // Start DFS from each node
    for (const node of this.nodes) {
      if (maxResults && uniqueMatches.size >= maxResults) break;
      generatePaths(node, [], 0);
    }

    // Convert unique matches map to array
    return Array.from(uniqueMatches.values());
  }

  /**
   * Main search method that searches both nodes and edges
   */
  search(
    pattern: string,
    options: SearchOptions = {},
    nodeFields: NodeSearchField[] = [NodeSearchField.SEQUENCE],
  ): SearchResults {
    const nodeMatches = this.searchNodes(pattern, nodeFields, options);
    const pathMatches = options.searchCrossNode
      ? this.searchPaths(pattern, options)
      : [];

    const totalNodeMatches = nodeMatches.reduce(
      (sum, match) => sum + match.totalMatches,
      0,
    );
    const totalPathMatches = pathMatches.reduce(
      (sum, match) => sum + match.totalMatches,
      0,
    );

    return {
      nodeMatches,
      pathMatches,
      totalNodeMatches,
      totalPathMatches,
      searchPattern: pattern,
      timestamp: Date.now(),
    };
  }
  /**
   * Get node by ID
   */
  getNode(nodeId: string): Node | undefined {
    return this.nodes.find((n) => n.id === nodeId);
  }

  /**
   * Get edge by ID
   */
  getEdge(edgeId: string): Edge | undefined {
    return this.edges.find((e) => e.id === edgeId);
  }

  /**
   * Get all connected edges for a node
   */
  getConnectedEdges(nodeId: string): Edge[] {
    return this.edges.filter(
      (edge) => edge.source === nodeId || edge.target === nodeId,
    );
  }

  /**
   * Get neighbor nodes (connected by edges)
   */
  getNeighborNodes(nodeId: string): Node[] {
    const connectedEdges = this.getConnectedEdges(nodeId);
    const neighborIds = new Set<string>();

    for (const edge of connectedEdges) {
      if (edge.source === nodeId) {
        neighborIds.add(edge.target);
      }
      if (edge.target === nodeId) {
        neighborIds.add(edge.source);
      }
    }

    return this.nodes.filter((node) => neighborIds.has(node.id));
  }

  /**
   * Update index with new nodes/edges
   */
  update(nodes: Node[], edges: Edge[]): void {
    this.nodes = nodes;
    this.edges = edges;
    this.nodeTextCache.clear();
    this.buildCache();
  }

  /**
   * Get statistics about the indexed data
   */
  getStats() {
    return {
      totalNodes: this.nodes.length,
      totalEdges: this.edges.length,
      cachedNodeFields: this.nodeTextCache.size,
    };
  }
}

/**
 * Create a search index from the store's nodes and edges
 */
export function createSearchIndex(
  nodes: Node[],
  edges: Edge[],
): DAGSearchIndex {
  return new DAGSearchIndex(nodes, edges);
}
