// Disclaimer: This code was generated by an AI language model, though checked and adjusted by a human.

/**
 * KMP (Knuth-Morris-Pratt) String Matching Algorithm
 * Uses dynamic programming to build a failure function for efficient pattern matching
 */

import type { MatchResult } from "./types.ts";

/**
 * Build the failure function (LPS - Longest Proper Prefix which is also Suffix)
 * This is the dynamic programming preprocessing step
 * Time Complexity: O(m) where m is pattern length
 * Space Complexity: O(m)
 */
export function buildFailureFunction(pattern: string): number[] {
  const m = pattern.length;
  const lps: number[] = new Array(m).fill(0);
  let len = 0; // length of previous longest prefix suffix
  let i = 1;

  while (i < m) {
    if (pattern[i] === pattern[len]) {
      len++;
      lps[i] = len;
      i++;
    } else {
      if (len !== 0) {
        // Consider the example: AAACAAAA and i = 7
        len = lps[len - 1];
      } else {
        lps[i] = 0;
        i++;
      }
    }
  }

  return lps;
}

/**
 * KMP Search - Find all occurrences of pattern in text
 * Time Complexity: O(n + m) where n is text length, m is pattern length
 * Space Complexity: O(m) for the failure function
 *
 * @param text - The text to search in
 * @param pattern - The pattern to search for
 * @returns Array of starting indices where pattern is found
 */
export function kmpSearch(text: string, pattern: string): number[] {
  if (!pattern || !text || pattern.length === 0) {
    return [];
  }

  // Normalize for case-insensitive search
  const searchText = text.toLowerCase();
  const searchPattern = pattern.toLowerCase();

  const n = searchText.length;
  const m = searchPattern.length;
  const matches: number[] = [];

  // Build failure function using dynamic programming
  const lps = buildFailureFunction(searchPattern);

  let i = 0; // index for text
  let j = 0; // index for pattern

  while (i < n) {
    if (searchPattern[j] === searchText[i]) {
      i++;
      j++;
    }

    if (j === m) {
      // Pattern found at index (i - j)
      matches.push(i - j);
      j = lps[j - 1];
    } else if (i < n && searchPattern[j] !== searchText[i]) {
      // Mismatch after j matches
      if (j !== 0) {
        // Use failure function to skip comparisons
        j = lps[j - 1];
      } else {
        i++;
      }
    }
  }

  return matches;
}

/**
 * Find all matches with context information
 *
 * @param text - The text to search in
 * @param pattern - The pattern to search for
 * @param contextLength - Number of characters to include before/after match (default: 10)
 * @returns Array of match results with context
 */
export function kmpSearchWithContext(
  text: string,
  pattern: string,
  contextLength: number = 10,
): MatchResult[] {
  const indices = kmpSearch(text, pattern);

  return indices.map((startIndex) => {
    const endIndex = startIndex + pattern.length;
    const contextStart = Math.max(0, startIndex - contextLength);
    const contextEnd = Math.min(text.length, endIndex + contextLength);

    return {
      startIndex,
      endIndex,
      matchedText: text.substring(startIndex, endIndex),
      contextBefore: text.substring(contextStart, startIndex),
      contextAfter: text.substring(endIndex, contextEnd),
    };
  });
}

/**
 * Check if pattern exists in text
 * Time Complexity: O(n + m)
 *
 * @param text - The text to search in
 * @param pattern - The pattern to search for
 * @returns true if pattern is found, false otherwise
 */
export function kmpContains(text: string, pattern: string): boolean {
  if (!pattern || !text || pattern.length === 0) {
    return false;
  }

  const searchText = text.toLowerCase();
  const searchPattern = pattern.toLowerCase();

  const n = searchText.length;
  const m = searchPattern.length;
  const lps = buildFailureFunction(searchPattern);

  let i = 0;
  let j = 0;

  while (i < n) {
    if (searchPattern[j] === searchText[i]) {
      i++;
      j++;
    }

    if (j === m) {
      return true; // Found a match
    } else if (i < n && searchPattern[j] !== searchText[i]) {
      if (j !== 0) {
        j = lps[j - 1];
      } else {
        i++;
      }
    }
  }

  return false;
}
