// Disclaimer: This code was generated by an AI language model, though checked and adjusted by a human.

import type { Node } from "@xyflow/react";

/**
 * Search field types for nodes
 */
export const NodeSearchField = {
  SEQUENCE: "sequence",
  PEPTIDES: "peptides",
  INTENSITIES: "intensities",
} as const;

export type NodeSearchField =
  (typeof NodeSearchField)[keyof typeof NodeSearchField];

/**
 * Match result with context
 */
export interface MatchResult {
  startIndex: number;
  endIndex: number;
  matchedText: string;
  contextBefore: string;
  contextAfter: string;
}

/**
 * Node match result
 */
export interface NodeMatch {
  nodeId: string;
  node: Node;
  field: string;
  matches: MatchResult[];
  totalMatches: number;
}

/**
 * Search result: a dictionary of nodeIds (strings) matching to arrays of tuples of indices (numbers) of matches in that node
 */
export interface SearchResultDict {
  [nodeId: string]: Array<{ startIndex: number; endIndex: number }>;
}

/**
 * Path match result (spanning multiple nodes)
 */
export interface PathMatch {
  path: Node[];
  pathIds: string[];
  combinedSequence: string;
  matches: MatchResult[];
  totalMatches: number;
  nodeMatches: {
    [nodeId: string]: Array<{ startIndex: number; endIndex: number }>;
  }; // Maps node IDs to array of match indices within that node
}

/**
 * Combined search results
 */
export interface SearchResults {
  nodeMatches: NodeMatch[];
  pathMatches: PathMatch[];
  totalNodeMatches: number;
  totalPathMatches: number;
  searchPattern: string;
  timestamp: number;
}

/**
 * Search options
 */
export interface SearchOptions {
  contextLength?: number;
  nodeFields?: NodeSearchField[];
  maxResults?: number;
  searchCrossNode?: boolean; // Enable searching across node boundaries
  maxPathLength?: number; // Maximum path length for cross-node search (default: 5)
}
