// Disclaimer: This code was generated by an AI language model, though checked and adjusted by a human.

import type { Node } from "@xyflow/react";

/**
 * Search field types for nodes
 */
export const NodeSearchField = {
  SEQUENCE: "sequence",
  PEPTIDES: "peptides",
  INTENSITIES: "intensities",
} as const;

export type NodeSearchField =
  (typeof NodeSearchField)[keyof typeof NodeSearchField];

/**
 * Match result with context
 */
export interface MatchResult {
  startIndex: number;
  endIndex: number;
  matchedText: string;
  contextBefore: string;
  contextAfter: string;
}

/**
 * Search result: a dictionary of nodeIds (strings) matching to tuples of indices (numbers) of match in that node
 */
export interface SearchResultDict {
  [nodeId: string]: Array<{ startIndex: number; endIndex: number }>;
}

/**
 * Path match result (spanning multiple nodes)
 */
export interface PathMatch {
  path: Node[];
  pathIds: string[];
  combinedSequence: string;
  matches: MatchResult[];
  totalMatches: number;
  nodeMatches: SearchResultDict;
}

export interface SearchResult {
  totalMatches: number;
  numberOfNodesMatched: number;
  nodeMatches: SearchResultDict; // Maps node IDs to match indices within that node
}

/**
 * Search options
 */
export interface SearchOptions {
  contextLength?: number;
  nodeFields?: NodeSearchField[];
  maxPathLength?: number; // Maximum path length for cross-node search (default: 5)
}
