export const tooltips = {
  peptideFile:
    "Select a csv file with peptide and intensity information. It should have the format: Sample,Protein ID,Sequence,Intensity. " +
    "Only the peptides that belong to the protein (including isoforms) from the EMBL-Entry will be searched on the graph. " +
    "Intensity will not be displayed automatically, make sure the intensity checkbox is clicked for this.",
  metadataFile:
    "Select a csv file with metadata information for the peptide file. It should have the format: Sample,Column1,...,ColumnX. Column{N} may then be selected as comparison column.",
  compareColumn:
    "Select the column from the metadata file which will be used to compare the intensities of the different categories",
  mergePeptides:
    "Set if only the longest peptide sequence should be added to the peptide attribute of a node/edge when at least one other " +
    "peptide sequence starts and ends inside (including the first/last peptide) the displayed peptide sequence. " +
    "This means that the longest peptide sequence will be a singular node rather than cut when a sub-peptide-sequence would start/end. " +
    "E. g. given ABCD and BC would lead to a node ABCD rather than A-BC-D.",
  OAggregation:
    "Select the peptide intensity aggregation when there are overlapping different peptides with (different) intensities on one node/edge. " +
    "Accepted options are: sum, mean, low median or high median. (Low median takes the lower median in case of an even number of values, high median the higher one.)" +
    "If not set, all peptide intensities are displayed like this: XX, ..., ZZ " +
    "Important: This method is not compatible with selecting a compare column. Please choose either of them. If both are chosen, only compare column will be set.",
  FileName:
    "Optional, if not set, the file will be saved with the name of the protein." +
    "The file name with which it will be saved in /data. Example: enter 'P10636_cancer_research' will create a file named 'P10636_cancer_research.graphml' in /data. ",
  substitute:
    "Mass spectrometry cannot distinguish isoleucine (I) from leucine (L). Enable this option to substitute both with 'J' so they are treated as equivalent in peptide matching.",
  collapse:
    "Toggle whether collapsed edges should be included in the graph. When digestion is active, collapsed edges may be recommended for clarity.",
  variant:
    "Include natural sequence variants from UniProt (identifier: VARIANT). These represent natural variations in protein sequences found in different organisms or individuals.",
  mutagen:
    "Include mutagenesis sites from UniProt (identifier: MUTAGEN). These mark amino acids that have been experimentally modified in mutagenesis studies.",
  conflict:
    "Include sequence conflicts from UniProt (identifier: CONFLICT). These indicate positions where different database sources report different amino acids.",
  initialMethionine:
    "Include initial methionine processing from UniProt (identifier: INIT_MET). This marks whether the initial methionine residue is removed post-translationally.",
  signalPeptide:
    "Include signal peptides from UniProt (identifier: SIGNAL). Signal peptides are N-terminal targeting sequences that direct proteins to the secretory pathway and are typically cleaved off.",
  proPeptide:
    "Include pro-peptide cleavage sites from UniProt (identifier: PROPEP). A propeptide is a part of a protein that is cleaved during maturation or activation. Once cleaved, a propeptide generally has no independent biological function.",
  polypeptideChain:
    "Include polypeptide chains from UniProt (identifier: CHAIN). This marks the extent of mature chains in proteins that undergo proteolytic processing to generate multiple functional chains.",
  peptide:
    "Include bioactive peptides from UniProt (identifier: PEPTIDE). This marks regions that form active peptides, often generated by proteolytic cleavage.",
};
